package com.matheo.flashcardcompanion.ui

/**
 * FR/EN string table, generated from the web UI's i18n.js so the two cannot
 * drift apart. French is canonical.
 *
 * A {name} placeholder is substituted by [t]. A value written
 * "singular|plural" is a plural pair, selected by [tn].
 *
 * Regenerate with tools/gen_strings.js after editing i18n.js.
 */
object Strings {
    val fr: Map<String, String> = mapOf(
        "nav.home" to "Accueil",
        "nav.courses" to "Cours",
        "nav.exams" to "Examens",
        "nav.stats" to "Statistiques",
        "nav.settings" to "Réglages",
        "nav.theme" to "Thème",
        "nav.menu" to "Menu",
        "nav.language" to "Langue",
        "health.online" to "En ligne",
        "health.offline" to "Hors ligne",
        "common.back" to "Retour",
        "common.close" to "Fermer",
        "common.cancel" to "Annuler",
        "common.error" to "erreur",
        "rate.again" to "Encore",
        "rate.hard" to "Difficile",
        "rate.good" to "Correct",
        "rate.easy" to "Facile",
        "home.today" to "Aujourd'hui",
        "home.loading" to "Chargement…",
        "home.crumbRoot" to "Accueil",
        "home.folder" to "dossier|dossiers",
        "home.deck" to "deck|decks",
        "home.subtitle" to "{due} carte{dueS} due{dueS} · {count} {noun}",
        "home.empty" to "Vide ici. Vérifie que Syncthing a copié les .apkg dans le dossier Flashcards.",
        "home.cardCount" to "{n} cartes",
        "home.upToDate" to " · à jour",
        "home.reviewAll" to "Réviser tout",
        "home.reviewScoped" to "Réviser · {name}",
        "home.newFolder" to "Nouveau dossier",
        "home.addSubjects" to "Ajouter",
        "home.addSubjectsTitle" to "Ajouter à « {name} »",
        "home.removeSubjects" to "Retirer",
        "home.removeSubjectsTitle" to "Retirer de « {name} »",
        "home.pickSubjects" to "Choisis les matières à y ranger.",
        "home.renameFolder" to "Renommer",
        "home.dissolveFolder" to "Dissoudre le dossier",
        "home.newFolderTitle" to "Nouveau dossier",
        "home.renameFolderTitle" to "Renommer le dossier",
        "home.folderNameLabel" to "Nom du dossier",
        "home.dissolveTitle" to "Dissoudre « {name} » ?",
        "home.dissolveBody" to "Les matières remontent à la racine. Aucune carte, aucune révision n'est touchée.",
        "home.cancel" to "Annuler",
        "home.confirm" to "Confirmer",
        "home.directCards" to "Cartes directes",
        "home.archive" to "Archiver",
        "home.archiveTitle" to "Archiver",
        "home.archiveNote" to "Choisis les matières ou dossiers à archiver.",
        "home.archiveFolder" to "Archiver le dossier",
        "home.archiveFolderTitle" to "Archiver « {name} » ?",
        "home.archiveFolderBody" to "Toutes ses matières quittent l'accueil et les révisions. Le dossier est conservé tel quel : le désarchivage le restaure à l'identique.",
        "home.archivesTitle" to "Archives",
        "home.archivesSub" to "Hors de l'accueil et hors des révisions. L'historique est conservé.",
        "home.archivedMeta" to "archivé",
        "home.unarchive" to "Désarchiver",
        "offline.title" to "Backend hors ligne",
        "offline.desc" to "Le serveur local ne répond pas sur",
        "offline.restartHead" to "Pour redémarrer",
        "offline.step1pre" to "Ouvre ",
        "offline.step2pre" to "Lance ",
        "offline.retry" to "Réessayer",
        "courses.title" to "PDF de cours",
        "courses.sub" to "Un dossier par matière, retrouvé automatiquement à partir des decks — pas garanti à 100%.",
        "courses.loadError" to "Impossible de charger les cours.",
        "courses.noSubjects" to "Aucune matière trouvée.",
        "courses.noPdf" to "Aucun PDF trouvé.",
        "exams.newTitle" to "Nouvel examen",
        "exams.newSub" to "Matière (choisie parmi tes decks) et date approximative des résultats.",
        "exams.subject" to "Matière",
        "exams.pickSubject" to "Choisir une matière…",
        "exams.expectedResults" to "Résultats attendus",
        "exams.add" to "Ajouter",
        "exams.corrTitle" to "Corrélation par matière",
        "exams.corrSub" to "Note obtenue, % de réussite en révision, temps investi — trois chiffres indépendants, pas de score composite : c'est à vous de juger.",
        "exams.thResults" to "Résultats",
        "exams.thGrade" to "Note",
        "exams.thSuccess" to "Réussite",
        "exams.thTime" to "Temps investi",
        "exams.empty" to "Aucun examen enregistré pour l'instant.",
        "exams.adding" to "Ajout…",
        "exams.added" to "Ajouté.",
        "exams.addFailed" to "Échec de l'ajout.",
        "stats.overviewTitle" to "Vue d'ensemble",
        "stats.overviewSub" to "Historique complet des révisions, jamais purgé.",
        "stats.reviews" to "révisions",
        "stats.totalTime" to "temps total",
        "stats.successRate" to "réussite",
        "stats.daysTitle" to "Jours de révision",
        "stats.noReviews" to "Pas encore de révision enregistrée.",
        "stats.export" to "Export",
        "stats.perCard" to "Par carte",
        "stats.thCard" to "Carte",
        "stats.thReviews" to "Révisions",
        "stats.thSuccess" to "Réussite",
        "stats.thAvgTime" to "Tps moy.",
        "stats.thTotalTime" to "Tps total",
        "stats.thLastGrade" to "Dern. note",
        "stats.thLastReview" to "Dernière révision",
        "stats.noCards" to "Aucune carte révisée pour l'instant.",
        "stats.dayCellTitle" to "{date} · {n} révision{s}",
        "stats.dayHigh" to "Jour le plus haut : ",
        "stats.dayLow" to "Jour le plus bas : ",
        "settings.sm2Sub" to "Intervalles gradués (en jours) appliqués dès la 1ʳᵉ révision, et bonus des cartes matures.",
        "settings.easyBonus" to "Bonus Facile",
        "settings.unitDays" to "j",
        "settings.notifTitle" to "Notifications",
        "settings.notifSub" to "Heure du rappel quotidien s'il reste des cartes dues (Termux, local, sans Google).",
        "settings.reminderHour" to "Heure du rappel",
        "settings.save" to "Enregistrer",
        "settings.loadError" to "Impossible de charger les réglages.",
        "settings.saving" to "Enregistrement…",
        "settings.saved" to "Enregistré.",
        "settings.saveFailed" to "Échec de l'enregistrement.",
        "review.recto" to "Recto",
        "review.tapReveal" to "Touchez pour révéler",
        "review.verso" to "Verso",
        "review.tapToAnswer" to "Touchez la carte pour répondre",
        "review.sessionDone" to "Session terminée",
        "review.allReviewed" to "Toutes les cartes dues ont été revues.",
        "review.backToDecks" to "Retour aux decks",
        "review.deepExplTitle" to "Explication approfondie",
        "review.explainBtn" to "Explique en profondeur",
        "review.allDecks" to "Tous les decks",
        "review.viewSource" to "Voir le cours source",
        "review.cardsReviewed" to "{n} carte{s} revue{s}.",
        "review.nothingToReview" to "Rien à réviser ici pour le moment.",
        "review.groundedIn" to "Ancré dans {files}",
        "review.noSourceChip" to "Sans source PDF · carte seule",
        "review.noSourceBand" to "Aucun PDF source n'a pu être associé à cette carte. L'explication est générée à partir du recto/verso seulement — recoupe avec ton cours.",
        "review.explainError" to "Impossible de générer l'explication. Vérifie que le backend et la clé Infercom sont OK.",
        "review.fbQuestion" to "Utile ?",
        "review.fbUp" to "Utile",
        "review.fbDown" to "Pas utile",
        "review.fbThanks" to "Merci, c'est noté",
        "review.critiqueTitle" to "Qu'est-ce qui n'allait pas ?",
        "review.critiquePlaceholder" to "Ce qui manquait ou était faux…",
        "review.critiqueSend" to "Régénérer",
        "pdf.helpFab" to "Besoin d'aide",
        "pdf.prevPage" to "Page précédente",
        "pdf.nextPage" to "Page suivante",
        "pdf.askPlaceholder" to "Pose une question sur ce cours…",
        "pdf.noCourse" to "Aucun cours spécifié.",
        "pdf.loading" to "Chargement du PDF…",
        "pdf.loadError" to "Impossible de charger ce PDF.",
        "pdf.modelFallback" to "modèle",
        "pdf.cached" to "en cache",
        "pdf.freshGen" to "généré à l'instant",
        "pdf.helpError" to "Impossible d'obtenir une réponse. Vérifie que le backend et la clé Infercom sont OK.",
    )

    val en: Map<String, String> = mapOf(
        "nav.home" to "Home",
        "nav.courses" to "Courses",
        "nav.exams" to "Exams",
        "nav.stats" to "Statistics",
        "nav.settings" to "Settings",
        "nav.theme" to "Theme",
        "nav.menu" to "Menu",
        "nav.language" to "Language",
        "health.online" to "Online",
        "health.offline" to "Offline",
        "common.back" to "Back",
        "common.close" to "Close",
        "common.cancel" to "Cancel",
        "common.error" to "error",
        "rate.again" to "Again",
        "rate.hard" to "Hard",
        "rate.good" to "Good",
        "rate.easy" to "Easy",
        "home.today" to "Today",
        "home.loading" to "Loading…",
        "home.crumbRoot" to "Home",
        "home.folder" to "folder|folders",
        "home.deck" to "deck|decks",
        "home.subtitle" to "{due} card{dueS} due · {count} {noun}",
        "home.empty" to "Nothing here. Check that Syncthing copied the .apkg files into the Flashcards folder.",
        "home.cardCount" to "{n} cards",
        "home.upToDate" to " · up to date",
        "home.reviewAll" to "Review all",
        "home.reviewScoped" to "Review · {name}",
        "home.newFolder" to "New folder",
        "home.addSubjects" to "Add",
        "home.addSubjectsTitle" to "Add to “{name}”",
        "home.removeSubjects" to "Remove",
        "home.removeSubjectsTitle" to "Remove from “{name}”",
        "home.pickSubjects" to "Pick the subjects to file into it.",
        "home.renameFolder" to "Rename",
        "home.dissolveFolder" to "Dissolve the folder",
        "home.newFolderTitle" to "New folder",
        "home.renameFolderTitle" to "Rename the folder",
        "home.folderNameLabel" to "Folder name",
        "home.dissolveTitle" to "Dissolve “{name}”?",
        "home.dissolveBody" to "Its subjects return to the root. No card and no review is touched.",
        "home.cancel" to "Cancel",
        "home.confirm" to "Confirm",
        "home.directCards" to "Direct cards",
        "home.archive" to "Archive",
        "home.archiveTitle" to "Archive",
        "home.archiveNote" to "Pick the subjects or folders to archive.",
        "home.archiveFolder" to "Archive the folder",
        "home.archiveFolderTitle" to "Archive “{name}”?",
        "home.archiveFolderBody" to "All its subjects leave the home screen and the reviews. The folder itself is kept as it is: unarchiving restores it identically.",
        "home.archivesTitle" to "Archives",
        "home.archivesSub" to "Out of the home screen and out of the reviews. The history is kept.",
        "home.archivedMeta" to "archived",
        "home.unarchive" to "Unarchive",
        "offline.title" to "Backend offline",
        "offline.desc" to "The local server is not responding on",
        "offline.restartHead" to "To restart",
        "offline.step1pre" to "Open ",
        "offline.step2pre" to "Run ",
        "offline.retry" to "Retry",
        "courses.title" to "Course PDFs",
        "courses.sub" to "One folder per subject, matched automatically from the decks — not 100% guaranteed.",
        "courses.loadError" to "Could not load the courses.",
        "courses.noSubjects" to "No subject found.",
        "courses.noPdf" to "No PDF found.",
        "exams.newTitle" to "New exam",
        "exams.newSub" to "Subject (picked from your decks) and approximate date of the results.",
        "exams.subject" to "Subject",
        "exams.pickSubject" to "Choose a subject…",
        "exams.expectedResults" to "Expected results",
        "exams.add" to "Add",
        "exams.corrTitle" to "Correlation by subject",
        "exams.corrSub" to "Grade obtained, % review success, time invested — three independent figures, no composite score: it's up to you to judge.",
        "exams.thResults" to "Results",
        "exams.thGrade" to "Grade",
        "exams.thSuccess" to "Success",
        "exams.thTime" to "Time invested",
        "exams.empty" to "No exam recorded yet.",
        "exams.adding" to "Adding…",
        "exams.added" to "Added.",
        "exams.addFailed" to "Failed to add.",
        "stats.overviewTitle" to "Overview",
        "stats.overviewSub" to "Full review history, never purged.",
        "stats.reviews" to "reviews",
        "stats.totalTime" to "total time",
        "stats.successRate" to "success",
        "stats.daysTitle" to "Review days",
        "stats.noReviews" to "No review recorded yet.",
        "stats.export" to "Export",
        "stats.perCard" to "Per card",
        "stats.thCard" to "Card",
        "stats.thReviews" to "Reviews",
        "stats.thSuccess" to "Success",
        "stats.thAvgTime" to "Avg time",
        "stats.thTotalTime" to "Total time",
        "stats.thLastGrade" to "Last grade",
        "stats.thLastReview" to "Last review",
        "stats.noCards" to "No card reviewed yet.",
        "stats.dayCellTitle" to "{date} · {n} review{s}",
        "stats.dayHigh" to "Highest day: ",
        "stats.dayLow" to "Lowest day: ",
        "settings.sm2Sub" to "Graduated intervals (in days) applied from the 1st review, plus a bonus for mature cards.",
        "settings.easyBonus" to "Easy bonus",
        "settings.unitDays" to "d",
        "settings.notifTitle" to "Notifications",
        "settings.notifSub" to "Time of the daily reminder if due cards remain (Termux, local, no Google).",
        "settings.reminderHour" to "Reminder time",
        "settings.save" to "Save",
        "settings.loadError" to "Could not load the settings.",
        "settings.saving" to "Saving…",
        "settings.saved" to "Saved.",
        "settings.saveFailed" to "Failed to save.",
        "review.recto" to "Front",
        "review.tapReveal" to "Tap to reveal",
        "review.verso" to "Back",
        "review.tapToAnswer" to "Tap the card to answer",
        "review.sessionDone" to "Session complete",
        "review.allReviewed" to "All due cards have been reviewed.",
        "review.backToDecks" to "Back to decks",
        "review.deepExplTitle" to "In-depth explanation",
        "review.explainBtn" to "Explain in depth",
        "review.allDecks" to "All decks",
        "review.viewSource" to "View source course",
        "review.cardsReviewed" to "{n} card{s} reviewed.",
        "review.nothingToReview" to "Nothing to review here right now.",
        "review.groundedIn" to "Grounded in {files}",
        "review.noSourceChip" to "No PDF source · card only",
        "review.noSourceBand" to "No source PDF could be matched to this card. The explanation is generated from the front/back only — cross-check with your course.",
        "review.explainError" to "Could not generate the explanation. Check that the backend and the Infercom key are OK.",
        "review.fbQuestion" to "Helpful?",
        "review.fbUp" to "Helpful",
        "review.fbDown" to "Not helpful",
        "review.fbThanks" to "Thanks, noted",
        "review.critiqueTitle" to "What was off or wrong?",
        "review.critiquePlaceholder" to "What was missing or incorrect…",
        "review.critiqueSend" to "Regenerate",
        "pdf.helpFab" to "Need help",
        "pdf.prevPage" to "Previous page",
        "pdf.nextPage" to "Next page",
        "pdf.askPlaceholder" to "Ask a question about this course…",
        "pdf.noCourse" to "No course specified.",
        "pdf.loading" to "Loading PDF…",
        "pdf.loadError" to "Could not load this PDF.",
        "pdf.modelFallback" to "model",
        "pdf.cached" to "cached",
        "pdf.freshGen" to "just generated",
        "pdf.helpError" to "Could not get an answer. Check that the backend and the Infercom key are OK.",
    )
}
